language: node_js
node_js:
    - "8"

addons:
  apt:
    packages:
    - ldap-utils
    - slapd
  hosts:
      - travis.my-domain.com

before_install:
    # - tests/travis/ldap-setup.sh
    - sed -i -e '/^server/ s/389/3389/' -e 's/^server.*636$//' config/ldap.ini
    - mkdir /tmp/slapd
    - slapd -f tests/travis/slapd.conf -h ldap://localhost:3389 &
    - sleep 3
    - ldapadd -x -D "cn=admin,dc=my-domain,dc=com" -w "rAR84,NZ=F" -h localhost:3389 -f tests/env/testdata.ldif

services:
# https://docs.travis-ci.com/user/database-setup/
#  - mongodb
#  - elasticsearch
#  - redis-server

before_script:

script:
    - npm run lint
    - npm test

after_success:

# enable codecov, which doesn't currently work for plugins because
# plugins are run in vm.runInNewContext()
#
#   - npm install istanbul codecov
#   - npm run cover
#   - ./node_modules/.bin/codecov

sudo: false
